language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js: '8'
before_install:
- npm i -g npm5@latest
script:
- npm run lint
after_success:
- npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
