language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js: node
script:
- npm run lint
- make dist
after_success:
- npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
